### ISSUE TITLE
PostgreSQL connection on blenderkit.com/asset-earnings-live not working

### ISSUE THREAD

**Issue by Numbian** [BlenderKit/platform#3]
### Bug Description

I don't know if this is an "official page", but I used it to check what assets categories were in demand. Currently, the data is not loading though. Is there any chance you could fix it?

### Error Logs

![image](https://github.com/BlenderKit/blenderkit/assets/42476878/1ab41802-7ba9-466b-a20d-0cc8555ad7fb)

### Steps to Reproduce

1) Open https://www.blenderkit.com/asset-earnings-live/
2) Wait until full load

**Comment by PetrDlouhy** [comment]
Problem is with Google Looker studio (former Google Data studio) connecting to SQL database.
Probably this issue: https://stackoverflow.com/questions/76076042/connecting-heroku-postgres-to-google-studio-looker

We will look at this, but in the past the fix didn't last for long.

**Comment by Numbian** [comment]
Hi @PetrDlouhy, Thank you for your reply.
 
I don't know what I'm doing 😂, but you could try to take a look at this:
https://stackoverflow.com/questions/53191297/failed-to-connect-mysql-ssl-connection-to-google-data-studio

1) Google Data Studio's SSL configuration was not capable of connecting via TLSv1.2 or TLSv1.3. They fixed a similar problem by enabling TLSv1.1 in their SQL conf.

2) SSL connection in Data Studio, needs cert file in .pem file format instead of .crt format.

Anyway, shall I close this topic, if this is known issue without a solution?

**Comment by PetrDlouhy** [comment]
@Numbian No, please don't close this issue. We should solve this somehow. Only the solution might not be so quick and easy.

**Comment by Numbian** [comment]
@PetrDlouhy 
Ok, I linked to that stackoverflow topic because I thought that, if your fix worked and then stopped working, it could be somehow connected to SSL auto-renew and formats or the fact that TLSv1.1 got depriciated.

**Comment by Numbian** [comment]
@PetrDlouhy 
Or maybe it would be easier to just get rid of third-party services?

Just get json from database and present it on the front-end with javascript (like www.tabulator.info).
I guess even simple tables would be enough for this.

**Comment by PetrDlouhy** [comment]
@Numbian Problem is certificate rotation in Heroku PostgreSQL and non-flexibility of Looker studio in that regard.
Now it is fixed, but when the certificate will rotate, it would need to be re-configured.

This page was meant like quick solution to get creators more insights.
I am not sure how many people visits this page, so maybe it is not such a big priority. But maybe in the future we can think about designing some better creator statistics.

**Comment by agajdosi** [comment]
@Numbian Thanks for the [www.tabulator.info](http://www.tabulator.info/) tip. I agree that depending on 3rd party service is not ideal, but it is how it is for now. We have quite a few things to rollout, so remaking the graphs is not a priority right now, but as @PetrDlouhy said, maybe in future redesign to graphs would be nice. I agree.

Graphs should be working now, please confirm to us once you have some time, that it works for you.

Cert says it should be valid until notAfter=Nov 30 10:15:47 2033 GMT, but I cannot find any docs on Heroku if they renew that more frequently. If you face this problem in the future, please let us know.

**Comment by Numbian** [comment]
@PetrDlouhy @agajdosi
I confirm it is working now. 
I think I found this site a long time ago in your sitemap.xml (it's not there anymore) and I don't think many users know about it 😂 I just look at is once every few month to check if trends are still the same.
Thank you!

**Comment by agajdosi** [comment]
@Numbian Cool, you have some hacker spirit! Thanks for the report.
